#include <f2c/sys/sys.h>
#include <f2c/sys/vops.h>
#include <f2c/sys/ex.h>
#include <f2c/sys/gks.h>
#include <f2c/sys/ncar.h>
#include <f2c/tables/tbtables.h>
#include "../../lib/pttables/f2c_proto.h"
#include "../daolib/f2c_proto.h"
#include "../peak/f2c_proto.h"
#include "../daoedit/f2c_proto.h"
#include "../allstar/f2c_proto.h"
#include "f2c_proto.h"
