      SUBROUTINE CONOUT (IVER)
C                                                                               
C +-----------------------------------------------------------------+           
C |                                                                 |           
C |                Copyright (C) 1986 by UCAR                       |           
C |        University Corporation for Atmospheric Research          |           
C |                    All Rights Reserved                          |           
C |                                                                 |           
C |                 NCARGRAPHICS  Version 1.00                      |           
C |                                                                 |           
C +-----------------------------------------------------------------+           
C                                                                               
C                                                                               
C
C + NOAO - This routine is a no-op in IRAF.
C - NOAO
C
C  LIST OUT ALL THE CONRAN OPTION VALUES ON THE LINE PRINTER
C
C  THE VALUE OF IVER DETERMINES WHICH ENTRY POINT CALLED THIS ROUTINE
C
C 1. CONRAQ
C 2. CONRAN
C 3. CONRAS
C
C
C
      COMMON /CONRA1/ CL(30)     ,NCL        ,OLDZ       ,PV(210)    ,
     1                FINC       ,HI         ,FLO
      COMMON /CONRA2/ REPEAT     ,EXTRAP     ,PER        ,MESS       ,
     1                ISCALE     ,LOOK       ,PLDVLS     ,GRD        ,
     2                CINC       ,CHILO      ,CON        ,LABON      ,
     3                PMIMX      ,SCALE      ,FRADV      ,EXTRI      ,
     4                BPSIZ      ,LISTOP
      COMMON /CONRA3/ IREC
      COMMON /CONRA4/ NCP        ,NCPSZ
      COMMON /CONRA5/ NIT        ,ITIPV
      COMMON /CONRA6/ XST        ,YST        ,XED        ,YED        ,
     1                STPSZ      ,IGRAD      ,IG         ,XRG        ,
     2                YRG        ,BORD       ,PXST       ,PYST       ,
     3                PXED       ,PYED       ,ITICK
      COMMON /CONRA7/ TITLE      ,ICNT   ,ITLSIZ
      COMMON /CONRA8/ IHIGH      ,INMAJ      ,INLAB      ,INDAT      ,
     1              LEN      ,IFMT       ,LEND       ,
     2                IFMTD      ,ISIZEP     ,INMIN
      COMMON /CONRA9/ ICOORD(500),NP         ,MXXY       ,TR         ,
     1                BR         ,TL         ,BL         ,CONV       ,
     2                XN         ,YN         ,ITLL       ,IBLL       ,
     3                ITRL       ,IBRL       ,XC         ,YC         ,
     4                ITLOC(210) ,JX         ,JY         ,ILOC       ,
     5                ISHFCT     ,XO         ,YO         ,IOC        ,NC
      COMMON /CONR10/ NT         ,NL         ,NTNL       ,JWIPT      ,
     1                JWIWL      ,JWIWP      ,JWIPL      ,IPR        ,
     2                ITPV
      COMMON /CONR11/ NREP       ,NCRT       ,ISIZEL     ,
     1                MINGAP     ,ISIZEM         ,
     2                TENS
      COMMON /CONR12/ IXMAX      ,IYMAX      ,XMAX       ,YMAX
      LOGICAL         REPEAT     ,EXTRAP     ,PER        ,MESS       ,
     1                LOOK       ,PLDVLS     ,GRD        ,LABON      ,
     2                PMIMX      ,FRADV      ,EXTRI      ,CINC       ,
     3                TITLE      ,LISTOP     ,CHILO      ,CON
      COMMON /CONR13/XVS(50),YVS(50),ICOUNT,SPVAL,SHIELD,
     1               SLDPLT
      LOGICAL SHIELD,SLDPLT
      COMMON /CONR14/LINEAR
      LOGICAL LINEAR
      COMMON /CONR15/ ISTRNG
        CHARACTER*64 ISTRNG
        COMMON /CONR16/ FORM
        CHARACTER*10 FORM
        COMMON /CONR17/ NDASH, IDASH, EDASH
        CHARACTER*10 NDASH, IDASH, EDASH
C
      SAVE
C
C  GET THE STANDARD OUTPUT UNIT TO WRITE THE OPTION VALUE LIST
C
      IUNIT = I1MACH(2)
C
C  PRINT OUT HEADER AND ALL OPTIONS WHICH APPLY TO CALLING VERSION
C
C     GO TO ( 100, 110, 120),IVER
C 100 WRITE (IUNIT,1001)
C     GO TO  130
C 110 WRITE (IUNIT,1002)
C     GO TO  130
C 120 WRITE (IUNIT,1003)
C 130 WRITE (IUNIT,1004)
C
C  PERIMETER
C
C     WRITE (IUNIT,1005)
C     IF (PER) GO TO  140
C     WRITE (IUNIT,1006)
C     GO TO  150
C 140 WRITE (IUNIT,1007)
C
C  GRID
C
C 150 WRITE (IUNIT,1008)
C     IF (GRD) GO TO  160
C     WRITE (IUNIT,1009)
C     GO TO  170
C 160 WRITE (IUNIT,1010)
C
C  SCALING OF DATA ON FRAME
C
C 170 WRITE (IUNIT,1011)
C     GO TO ( 180, 190, 200),ISCALE+1
C 180 WRITE (IUNIT,1012)
C     GO TO  210
C 190 WRITE (IUNIT,1013)
C     GO TO  210
C 200 WRITE (IUNIT,1014)
C
C  SAME DATA ANOTHER PLOT
C
C 210 WRITE (IUNIT,1015)
C     IF (REPEAT) GO TO  220
C     WRITE (IUNIT,1016)
C     GO TO  230
C 220 WRITE (IUNIT,1017)
C
C  SHIELDING
C
C 230 WRITE(IUNIT,2000)
C     IF (SHIELD) GO TO 231
C     WRITE(IUNIT,2001)
C     GO TO 232
C 231 WRITE(IUNIT,2002)
C
C  INTERPOLATION
C
C 232 WRITE(IUNIT,2003)
C     IF (LINEAR) GO TO 233
C     WRITE(IUNIT,2004)
C     GO TO 234
C 233 WRITE(IUNIT,2005)
C
C  PLOT THE SHIELD
C
C 234 WRITE(IUNIT,2006)
C     IF (SLDPLT) GO TO 235
C     WRITE(IUNIT,2007)
C     GO TO 236
C 235 WRITE(IUNIT,2008)
C
C  EXTRAPOLATION
C
C 236 WRITE (IUNIT,1018)
C     IF (EXTRAP) GO TO  240
C     WRITE (IUNIT,1019)
C     GO TO  250
C 240 WRITE (IUNIT,1020)
C
C  STEP SIZE OR RESOLUTION OF THE GRID
C
C 250 WRITE (IUNIT,1021) IGRAD
C
C  MESSAGE AT BOTTOM OF PLOT
C
C     WRITE (IUNIT,1022)
C     IF (MESS) GO TO  260
C     WRITE (IUNIT,1023)
C     GO TO  270
C 260 WRITE (IUNIT,1024)
C
C  TITLE AT TOP OF PLOT
C
C 270 WRITE (IUNIT,1025)
C     IF (TITLE) GO TO  280
C     WRITE (IUNIT,1026)
C     GO TO  290
C 280 WRITE (IUNIT,1027)
C
C  SIZE OF TITLE
C
C 290 WRITE (IUNIT,1028) ITLSIZ
C
C  PRINT TITLE
C
C     IF (ICNT.EQ.0 .OR. .NOT.TITLE) GO TO  310
C     ICC = 100
C     IF (ICC .GT. ICNT) ICC = ICNT
C     WRITE (IUNIT,1029) ISTRNG
C
C  DATA POINTS USED FOR PARTIAL DERIVATIVE ESTIMATION
C
C 310 WRITE (IUNIT,1030) NCP
C
C  LOOK AT TRIANGLES SWITCH
C
C     WRITE (IUNIT,1031)
C     IF (LOOK) GO TO  320
C     WRITE (IUNIT,1032)
C     GO TO  330
C 320 WRITE (IUNIT,1033)
C
C  ADVANCE FRAME BEFORE PLOTTING TRIANGULATION
C
C 330 WRITE (IUNIT,1034)
C     IF (FRADV) GO TO  340
C     WRITE (IUNIT,1035)
C     GO TO  350
C 340 WRITE (IUNIT,1036)
C
C  TRIANGLES ONLY PLOT
C
C 350 WRITE (IUNIT,1037)
C     IF (EXTRI) GO TO  360
C     WRITE (IUNIT,1038)
C     GO TO  370
C 360 WRITE (IUNIT,1039)
C
C  PLOT THE INPUT DATA VALUES
C
C 370 WRITE (IUNIT,1040)
C     IF (PLDVLS) GO TO  380
C     WRITE (IUNIT,1041)
C     GO TO  390
C 380 WRITE (IUNIT,1042)
C
C  FORMAT OF THE PLOTTED INPUT DATA
C
C 390 WRITE (IUNIT,1043)
C     IF (LEN .NE. 0) GO TO  400
C     WRITE (IUNIT,1044)
C     GO TO  420
C 400 WRITE (IUNIT,1045) FORM
C
C  SIZE OF THE PLOTTED DATA VALUES
C
C 420 WRITE (IUNIT,1046) ISIZEP
C
C  INTENSITY SETTINGS
C
C     WRITE (IUNIT,1047)
C     WRITE (IUNIT,1048) INMAJ,INMIN,INLAB,INDAT
C
C  DISTLAY CONTOUR SETTING
C
C     WRITE (IUNIT,1049)
C     IF (CON) GO TO  430
C     WRITE (IUNIT,1050)
C     GO TO  440
C 430 WRITE (IUNIT,1051) NCL,(CL(I),I=1,NCL)
C
C  CONTOUR INCREMENT
C
C 440 WRITE (IUNIT,1052)
C     IF (CINC) GO TO  450
C     WRITE (IUNIT,1053)
C     GO TO  460
C 450 WRITE (IUNIT,1054) FINC
C
C  CONTOUR HIGH AND LOW VALUES
C
C 460 WRITE (IUNIT,1055)
C     IF (CHILO) GO TO  470
C     WRITE (IUNIT,1056)
C     GO TO  480
C 470 WRITE (IUNIT,1057) HI,FLO
C
C  CALL CONOT2 IF NOT QUICK VERSION
C
C 480 IF (IVER .NE. 1) CALL CONOT2 (IVER,IUNIT)
C
C  THE ROUTINE CONOT2 WAS GENERATED TO ELIMINATE COMPILER ERRORS
C  RESULTING FROM TOO MANY FORMAT STATEMENTS IN ONE SUBROUTINE
C
C     RETURN
C
C
C1001 FORMAT (1X,'CONRAQ')
C1002 FORMAT (1X,'CONRAN')
C1003 FORMAT (1X,'CONRAS')
C1004 FORMAT ('+',6X,'-OPTION VALUE SETTINGS',/
C    1        ,7X,'ALL NON-PWRIT VALUES APPLY TO THE UNSCALED DATA')
C1005 FORMAT (5X,'PERIMETER, PER=')
C1006 FORMAT ('+',19X,'OFF')
C1007 FORMAT ('+',19X,'ON')
C1008 FORMAT (5X,'GRID, GRD=')
C1009 FORMAT ('+',14X,'OFF')
C1010 FORMAT ('+',14X,'ON')
C1011 FORMAT (5X,'SCALING OF PLOT ON FRAME, SCA=')
C1012 FORMAT ('+',34X,'ON')
C1013 FORMAT ('+',34X,'OFF')
C1014 FORMAT ('+',34X,'PRI')
C1015 FORMAT (5X,'SAME DATA FOR ANOTHER PLOT, REP=')
C1016 FORMAT ('+',36X,'OFF')
C1017 FORMAT ('+',36X,'ON')
C1018 FORMAT (5X,'EXTRAPOLATION, EXT=')
C1019 FORMAT ('+',23X,'OFF')
C1020 FORMAT ('+',23X,'ON')
C1021 FORMAT (5X,'RESOLUTION, SSZ=',I4)
C1022 FORMAT (5X,'MESSAGE, MES=')
C1023 FORMAT ('+',17X,'OFF')
C1024 FORMAT ('+',17X,'ON')
C1025 FORMAT (5X,'TITLE, TLE=')
C1026 FORMAT ('+',15X,'OFF')
C1027 FORMAT ('+',15X,'ON')
C1028 FORMAT (5X,'TITLE SIZE IN PWRIT UNITS, STL=',I4)
C1029 FORMAT (5X,'TITLE=',A64)
C1030 FORMAT (5X,'DATA POINTS USED FOR PARTIAL DERIVATIVE',
C    1' ESTIMATION,  NCP=',I4)
C1031 FORMAT (5X,'LOOK AT TRIANGLES, TRI=')
C1032 FORMAT ('+',27X,'OFF')
C1033 FORMAT ('+',27X,'ON')
C1034 FORMAT (5X,'ADVANCE FRAME BEFORE PLOTTING TRIANGULATION,',
C    1' TFR=')
C1035 FORMAT ('+',53X,'OFF')
C1036 FORMAT ('+',53X,'ON')
C1037 FORMAT (5X,'TRIANGULATION ONLY PLOT, TOP=')
C1038 FORMAT ('+',33X,'OFF')
C1039 FORMAT ('+',33X,'ON')
C1040 FORMAT (5X,'PLOT THE INPUT DATA VALUES, PDV=')
C1041 FORMAT ('+',36X,'OFF')
C1042 FORMAT ('+',36X,'ON')
C1043 FORMAT (5X,'FORMAT OF THE PLOTTED INPUT DATA, FMT=')
C1044 FORMAT ('+',42X,'(G10.3)')
C1045 FORMAT ('+',42X,A10)
C1046 FORMAT (5X,'SIZE OF THE PLOTTED DATA VALUES IN PWRIT',
C    1' UNITS, SPD=',I4)
C1047 FORMAT (5X,'COLOR (INTENSITY) INDICES FOLLOW.',
C    1' FOR CONRAQ MAJOR CONTOURS ARE ONLY USED')
C1048 FORMAT (10X,'MAJOR CONTOUR LINES, MAJ=',I4,/
C    1        ,10X,'MINOR CONTOUR LINES, MIN=',I4,/
C    2        ,10X,'TITLE AND MESSAGE, LAB=',I4,/
C    3        ,10X,'PLOTTED DATA VALUES, DAT=',I4)
C1049 FORMAT (5X,'CONTOUR LEVELS,  CON=')
C1050 FORMAT ('+',25X,'OFF')
C1051 FORMAT ('+',25X,'ON, NCL=',I4,' ARRAY='/(10(2X,F10.3)))
C1052 FORMAT (5X,'CONTOUR INCREMENT, CIL=')
C1053 FORMAT ('+',27X,'OFF')
C 1054 FORMAT ('+',27X,'ON, INCREMENT=',G10.3)
C 1055 FORMAT (5X,'CONTOUR HIGH AND LOW VALUES, CHL=')
C 1056 FORMAT ('+',37X,'OFF')
C 1057 FORMAT ('+',37X,'ON, HI=',G10.3,' FLO=',G10.3)
C 2000 FORMAT (5X,'SHIELDING, SLD=')
C 2001 FORMAT ('+',19X,'OFF')
C 2002 FORMAT ('+',19X,'ON')
C 2003 FORMAT (5X,'INTERPOLATION, ITP=')
C 2004 FORMAT ('+',23X,'C1 SURFACE')
C 2005 FORMAT ('+',23X,'LINEAR')
C 2006 FORMAT (5X,'PLOT THE SHIELD, SPT=')
C 2007 FORMAT ('+',25X,'OFF')
C 2008 FORMAT ('+',25X,'ON')
C
      END
