#!/bin/sh
# 
#  SELF_INSTALL -- Simple script to automatically run the IRAF install script.
#
#  This is the setup script executed by the self-extacting installation
#  script following the unpacking of the tarball. The 'makeself' script
#  was written by Stéphane Peter (megastep at megastep.org) and is available
#  from
#               https://github.com/megastep/makeself
#
#  The command used to generate the self-extracting script was of the form:
#
#    % makeself.sh --base64 --notemp /<path>/iraf-v2.18/. \
#       iraf-v218-linux32.sh "NOIRLab IRAF v2.18 for 32-bit Linux" \
#       ./self_install
#

# Initialize the environment for the current directory/mach.
export iraf=${PWD}/
if [ -d bin.linux ]; then
    export IRAFARCH=linux
else
    export IRAFARCH=linux64
fi
export VERSION="v2.18"

# Run the IRAF install script, accepting all default prompts.
./install \
    --term xgterm \
    --mach linux  <<__EOF__






__EOF__

# Copy the X11IRAF files to the user login bin directory.
cp x11iraf/ximtool* $HOME/.iraf/bin
cp x11iraf/xgterm $HOME/.iraf/bin
cp x11iraf/ism_wcspix.e $HOME/.iraf/bin
cat x11iraf/XGterm.ad >> $HOME/.Xdefaults
if [ ! -f $HOME/.imtoolrc ]; then
    cp dev/imtoolrc $HOME/.imtoolrc
fi

