#!/bin/sh

set -e

branches="
  remove-java-classes
  Cleanup-external
  Remove-doswin
  Cleanup-local
  move_documentation_to_doc
  Remove-test-tar
  Further-cleanup
  fix-no-iraf-root
  Dont-remove-sticky-bit-for-tmp
  Cleanup-generated-files
  fix-osb-symlinks
  add-travis-ci
  use-sh-in-mklibs
  no-lib64
  build-vendor-before-novos
  linux64-zvsjmp
  vo-dir-structure
  remove-include-curl-types-h
  align-on-128bit-boundaries
  fix-fortran-declarations
  fix-i386-alloc
  fix-32bit-offset
  remove-x11iraf
  fix-scanlib-date-check
"
git checkout -f branch-merger-base
git branch -D merge-all || true
git checkout -b merge-all

for b in $branches ; do
    echo "******************" $b "******************" 
    git merge --no-edit $b
done
