      INTEGER FUNCTION ADDSET (C, STR, J, MAXSIZ)
      INTEGER J, MAXSIZ
      INTEGER C, STR (MAXSIZ)
      IF (.NOT.(J .GT. MAXSIZ))GOTO 23000
      ADDSET = 0
      GOTO 23001
23000 CONTINUE
      STR(J) = C
      J = J + 1
      ADDSET = 1
23001 CONTINUE
      RETURN
      END
