      SUBROUTINE CONCAT (BUF1, BUF2, OUTSTR)
      INTEGER BUF1(100), BUF2(100), OUTSTR(100)
      INTEGER I
      I = 1
      CALL STCOPY (BUF1, 1, OUTSTR, I)
      CALL SCOPY (BUF2, 1, OUTSTR, I)
      RETURN
      END
