      SUBROUTINE DELETE (SYMBOL, ST)
      INTEGER SYMBOL (100)
      INTEGER ST
      INTEGER MEM( 1)
      COMMON/CDSMEM/MEM
      INTEGER STLU
      INTEGER NODE, PRED
      IF (.NOT.(STLU (SYMBOL, NODE, PRED, ST) .EQ. 1))GOTO 23000
      MEM (PRED + 0) = MEM (NODE + 0)
      CALL DSFREE (NODE)
23000 CONTINUE
      RETURN
      END
