      SUBROUTINE DODASH (VALID, ARRAY, I, SET, J, MAXSET)
      INTEGER I, J, MAXSET
      INTEGER VALID (100), ARRAY (100), SET (MAXSET)
      INTEGER ESC
      INTEGER JUNK, K, LIMIT
      EXTERNAL INDEX
      INTEGER ADDSET, INDEX
      I = I + 1
      J = J - 1
      LIMIT = INDEX (VALID, ESC (ARRAY, I))
      K = INDEX (VALID, SET (J))
23000 IF (.NOT.(K .LE. LIMIT))GOTO 23002
      JUNK = ADDSET (VALID (K), SET, J, MAXSET)
23001 K = K + 1
      GOTO 23000
23002 CONTINUE
      RETURN
      END
