      SUBROUTINE FCOPY (IN, OUT)
      INTEGER IN, OUT
      INTEGER LINE (128)
      INTEGER GETLIN
23000 IF (.NOT.(GETLIN (LINE, IN) .NE. -1))GOTO 23001
      CALL PUTLIN (LINE, OUT)
      GOTO 23000
23001 CONTINUE
      RETURN
      END
