      INTEGER FUNCTION LOOKUP (SYMBOL, INFO, ST)
      INTEGER SYMBOL (100)
      INTEGER INFO (100)
      INTEGER ST
      INTEGER MEM( 1)
      COMMON/CDSMEM/MEM
      INTEGER I, NODSIZ, KLUGE
      INTEGER STLU
      INTEGER NODE, PRED
      IF (.NOT.(STLU (SYMBOL, NODE, PRED, ST) .EQ. 0))GOTO 23000
      LOOKUP = 0
      RETURN
23000 CONTINUE
      NODSIZ = MEM (ST)
      I = 1
23002 IF (.NOT.(I .LE. NODSIZ))GOTO 23004
      KLUGE = NODE + 1 - 1 + I
      INFO (I) = MEM (KLUGE)
23003 I = I + 1
      GOTO 23002
23004 CONTINUE
      LOOKUP = 1
      RETURN
      END
