      SUBROUTINE PROMPT (STR, BUF, FD)
      INTEGER STR(100), BUF(100)
      INTEGER FD
      INTEGER ISATTY
      IF (.NOT.(ISATTY(FD) .EQ. 1))GOTO 23000
      CALL PUTLIN (STR, FD)
      CALL RFFLUS(FD)
23000 CONTINUE
      CALL GETLIN (BUF, FD)
      RETURN
      END
