      SUBROUTINE RMTABL (ST)
      INTEGER ST
      INTEGER MEM( 1)
      COMMON/CDSMEM/MEM
      INTEGER I
      INTEGER WALKER, BUCKET, NODE
      BUCKET = ST
      DO 23000 I = 1, 43
      BUCKET = BUCKET + 1
      WALKER = MEM (BUCKET)
23002 IF (.NOT.(WALKER .NE. 0))GOTO 23003
      NODE = WALKER
      WALKER = MEM (NODE + 0)
      CALL DSFREE (NODE)
      GOTO 23002
23003 CONTINUE
23000 CONTINUE
23001 CONTINUE
      CALL DSFREE (ST)
      RETURN
      END
