      INTEGER FUNCTION SDROP (FROM, TO, CHARS)
      INTEGER FROM (100), TO (100)
      INTEGER CHARS
      INTEGER LEN, START
      INTEGER CTOC, LENGTH, MIN0
      LEN = LENGTH (FROM)
      IF (.NOT.(CHARS .LT. 0))GOTO 23000
      SDROP=(CTOC (FROM, TO, LEN + CHARS + 1))
      RETURN
23000 CONTINUE
      START = MIN0 (CHARS, LEN)
      SDROP=(CTOC (FROM (START + 1), TO, LEN + 1))
      RETURN
23001 CONTINUE
      END
