      INTEGER FUNCTION STAKE (FROM, TO, CHARS)
      INTEGER FROM (100), TO (100)
      INTEGER CHARS
      INTEGER LEN, START
      INTEGER LENGTH, CTOC, MAX0
      LEN = LENGTH (FROM)
      IF (.NOT.(CHARS .LT. 0))GOTO 23000
      START = MAX0 (LEN + CHARS, 0)
      STAKE=(CTOC (FROM (START + 1), TO, LEN + 1))
      RETURN
23000 CONTINUE
      STAKE=(CTOC (FROM, TO, CHARS + 1))
      RETURN
23001 CONTINUE
      END
