      INTEGER FUNCTION STCLOS (PAT, J, LASTJ, LASTCL)
      INTEGER PAT (128)
      INTEGER J, LASTJ, LASTCL
      INTEGER ADDSET
      INTEGER JP, JT, JUNK
      JP = J - 1
23000 IF (.NOT.(JP .GE. LASTJ))GOTO 23002
      JT = JP + 4
      JUNK = ADDSET (PAT (JP), PAT, JT, 128)
23001 JP = JP - 1
      GOTO 23000
23002 CONTINUE
      J = J + 4
      STCLOS = LASTJ
      JUNK = ADDSET (42, PAT, LASTJ, 128)
      JUNK = ADDSET (0, PAT, LASTJ, 128)
      JUNK = ADDSET (LASTCL, PAT, LASTJ, 128)
      JUNK = ADDSET (0, PAT, LASTJ, 128)
      RETURN
      END
