      INTEGER FUNCTION WKDAY (MONTH, DAY, YEAR)
      INTEGER MONTH, DAY, YEAR
      INTEGER LMONTH, LDAY, LYEAR
      LMONTH = MONTH - 2
      LDAY = DAY
      LYEAR = YEAR
      IF (.NOT.(LMONTH .LE. 0))GOTO 23000
      LMONTH = LMONTH + 12
      LYEAR = LYEAR - 1
23000 CONTINUE
      WKDAY = MOD (LDAY + (26 * LMONTH - 2) / 10 + LYEAR + LYEAR / 4 - 3
     *4, 7) + 1
      RETURN
      END
