#!/bin/csh -f
#

if (! $?iraf) then
    #echo ""
    #echo "Error:  You must have the iraf env variable defined !"
    #echo ""
    #exit 1

    set  iraf 	= $cwd/
endif


set  c_start	= `date`
/bin/rm -f spool */spool


$iraf/util/mkclean				# clean old binaries

cd $iraf/unix					# NOVOS bootstrap
source hlib/irafuser.csh
sh -x mkpkg.sh |& tee -a spool

cd $iraf/					# build NOVOS
mkpkg |& tee -a spool

cd $iraf/unix					# VOS bootstrap
source hlib/irafuser.csh
sh -x mkpkg.sh |& tee -a spool

cd $iraf/vendor					# build vendor libs
(make all |& tee -a ../spool.final)

cd $iraf/					# build core system
mkpkg |& tee -a ../spool.final

cd $iraf/noao					# build NOAO package
setenv noao $cwd/
mkpkg -p noao |& tee -a ../spool.final

/bin/rm -rf bin*/pkgconfig			# misc cleanup

set  c_end	= `date`


echo ""
echo ""
echo ""
echo "Start:  $c_start"
echo "  End:  $c_end"
