#!/bin/csh -f
#
#  PKGREPO - Get the repository base URI, either from the environment
#  variable 'IRAF_REPO' or the default.


if ($?IRAF_REPO) then
   echo $IRAF_REPO
else
   echo "ftp://iraf.noao.edu/iraf/v216/REPO"
endif

exit 0
