# Lexer common. This is necessary since the parser, generated by xyacc,
# does not allow any access to the lexer to initialize it, or to get
# variable values.

# Variables to initialize lexer
int	nlines				# line counter
int	pos				# character position in line
char	line[SZ_LINE]			# last line from file

# Variables returned by lexer
char	id[SZ_LINE]			# last identifier from lexer

common /lexcom/ nlines, pos, line, id
