# Copyright(c) 1986 Association of Universities for Research in Astronomy Inc.

# Image utilities process.

task	blkavg		= t_blkavg,
	blkrep		= t_blkrep,
	boxcar		= t_boxcar,
	chpixtype	= t_chpixtype,
	convolve	= t_convolve,
	hedit		= t_hedit,
	hselect		= t_hselect,
	fit1d		= t_fit1d,
	fmedian		= t_fmedian,
	fmode		= t_fmode,
	gauss		= t_gauss,
	geomap		= t_geomap,
	geotran		= t_geotran,
	gradient	= t_gradient,
	imarith		= t_imarith,
	imaxes		= t_imaxes,
	imcombine	= t_imcombine,
	imcopy		= t_imcopy,
	imdivide	= t_imdivide,
	imdelete	= t_imdelete,
	imexpr		= t_imexpr,
	imheader	= t_imheader,
	imhistogram	= t_imhistogram,
	imrename	= t_imrename,
	imshift		= t_imshift,
	imslice		= t_imslice,
	imstack		= t_imstack,
	imstatistics	= t_imstatistics,
	imsurfit	= t_imsurfit,
	imsum		= t_imsum,
	imtranspose	= t_imtranspose,
	laplace		= t_laplace,
	lineclean	= t_lineclean,
	listpixels	= t_listpixels,
	magnify		= t_magnify,
	median		= t_median,
	minmax		= t_minmax,
	mode		= t_mode,
	sections	= t_sections,
	shiftlines	= t_shiftlines,
	imgets		= t_imgets,
	xregister	= t_xregister
