#!/bin/csh -f

unalias ps egrep java

set dir   = `dirname $0`
set me    = `whoami`
set pid   = `ps -fwu $me | egrep -i hub | egrep -i jsamp` 	#  MACHDEP
set npid  = $#pid
set jar   = jsamp-1.3-2.jar

set mode  = "-mode client-gui"

if ($#argv > 0) then
    if ("$2" == "-no-gui") then
	set mode = "-mode no-gui"
        if (! ($?DISPLAY)) then
            setenv DISPLAY :0
        endif
    endif

    if ("$1" == "-bg") then
        if ($npid == 0) then
            /bin/rm -rf ~/.samp
            exec java -jar ${dir}/$jar hub ${mode} &
        endif

    else if ("$1" == "-kill") then
        kill -9 $pid[2]
        /bin/rm -rf ~/.samp

    else if ("$1" == "-status") then
        if ($npid == 0) then
	    echo "off"
        else
	    echo "on"
        endif

    endif
else
    if ($npid == 0) then
        /bin/rm -rf ~/.samp
        exec java -jar ${dir}/$jar hub ${mode}
    endif
endif
