#include <f2c/sys/sys.h>
#include <f2c/sys/vops.h>
#include <f2c/sys/ex.h>
#include <f2c/math/curfit.h>
#include <f2c/math/iminterp.h>
#include <f2c/math/nlfit.h>
#include <f2c/math/llsq.h>
#include <f2c/pkg/xtools.h>
#include <f2c/noao/smw.h>
#include <f2c/noao/asttools.h>
#include "f2c_proto.h"
