#!/bin/bash

bins=("cygwin" "freebsd" "linux" "linux64" "macintel" "macosx" "sunos")
for i in ${bins[@]}; do
    touch bin.$i/IRAF.NET
    touch noao/bin.$i/IRAF.NET
done

touch bin.cygwin/IB.CYGW.x86
touch bin.freebsd/IB.FBSD.x86
touch bin.linux/IB.LNUX.x86
touch bin.linux64/IB.LNUX.x86_64
touch bin.macintel/IB.MACX.x86_64
touch bin.macosx/IB.MACX.UNI
touch bin.sunos/IB.SSUN.x86
touch bin.ipad/IB.IPAD.ARM

touch noao/bin.cygwin/NB.CYGW.x86
touch noao/bin.freebsd/NB.FBSD.x86
touch noao/bin.linux/NB.LNUX.x86
touch noao/bin.linux64/NB.LNUX.x86_64
touch noao/bin.macintel/NB.MACX.x86_64
touch noao/bin.macosx/NB.MACX.UNI
touch noao/bin.sunos/NB.SSUN.x86
touch noao/bin.ipad/NB.IPAD.ARM

