#!/bin/bash

bins=("linux" "linux64" "macintel" "macosx")
for i in ${bins[@]}; do
    touch bin.$i/IRAF.NET
    touch noao/bin.$i/IRAF.NET
done

touch bin.linux/IB.LNUX.x86
touch bin.linux64/IB.LNUX.x86_64
touch bin.macintel/IB.MACX.x86_64
touch bin.macosx/IB.MACX.UNI

touch noao/bin.linux/NB.LNUX.x86
touch noao/bin.linux64/NB.LNUX.x86_64
touch noao/bin.macintel/NB.MACX.x86_64
touch noao/bin.macosx/NB.MACX.UNI

