#!/bin/csh -f
#

set  iraf 	= $cwd/

cd $iraf/				# build core system
mkpkg -x

cd $iraf/noao				# build NOAO package
setenv noao $cwd/
mkpkg -x -p noao

cd $iraf/vo				# build VO package
setenv vo $cwd/
mkpkg -x -p vo
