#!/bin/bash
#
#  PKGCONFIG -- Re-create the system Makefile to take into account new
#  packages.


# Initialize the $iraf and environment.
if [ -z "$iraf" ]; then
  if [ -e "$HOME/.iraf/setup.sh" ]; then
    source $HOME/.iraf/setup.sh
  else
    source unix/hlib/setup.sh
  fi
else
    source $iraf/unix/hlib/setup.sh
fi


/bin/echo "Initializing repository data ...."
$iraf/util/pkginit				# init repository information
if (( $? == 1 )); then
   exit
fi

# Create the template Makefile.
/bin/echo "Creating system makefile ...."
cp Makefile.tmpl Makefile
echo "Setup Complete."


# For each package we have, append a makefile entry.
pkg=`cat .repo_pkgs`
for p in ${pkg[@]} ; do

   # Create template makefile entries for each package
   /bin/echo "${p}::"					>> Makefile
   /bin/echo "	@../util/pkginst $p"			>> Makefile
   /bin/echo "clean_${p}::"				>> Makefile
   /bin/echo "	@../util/pkgclean $p"			>> Makefile
   /bin/echo "update_${p}::"				>> Makefile
   /bin/echo "	@../util/pkgupdate $p"			>> Makefile
   /bin/echo ""						>> Makefile

   # Create the directory
   if [ -e "$p" ]; then
      /bin/rm -rf $p
   fi
   mkdir $p
done

/bin/echo ""
exit 0
