#!/bin/csh -f
#
#  PKGDEL -- Delete an external package from the dynamic directory.
#
#


set  bindir	= "`dirname $0`"	# get iraf root
set  irafdir	= $bindir:h



if (-e $1) then
    /bin/rm -rf $1		>& /dev/null
endif

exit 0
