#!/bin/sh
#
#  PKGENV -- Initialize the package environment


rm -f .installed .zzsetenv.def

files=$(cat .repo_pkgs)
for p in $files ; do

    if [ -e "$p/.installed" ]; then
	cat "$p/.installed" 			>> .installed
	echo "reset $p	=$(pwd)/$p/"		>> .zzsetenv.def
    fi
done
echo "keep"					>> .zzsetenv.def
