#!/bin/csh -f
#
#  PKGENV -- Initialize the package environment


/bin/rm -f .installed .zzsetenv.def

foreach p ( `cat .repo_pkgs` )

    if (-e $p/.installed) then
	cat $p/.installed 		>> .installed
	echo "reset  $p	= $cwd/$p/"	>> .zzsetenv.def
    endif
end
echo "keep"				>> .zzsetenv.def
