#!/bin/bash
#
#  PKGREPO - Get the repository base URI, either from the environment
#  variable 'IRAF_REPO' or the default.


if [ -z "$IRAF_REPO" ]; then
   /bin/echo "ftp://iraf.noao.edu/iraf/v216/REPO"
else
   /bin/echo $IRAF_REPO
fi

exit 0
