extern int zdvall_(short *aliases, int *allflg, int *status);
extern int zdvown_(short *device, short *owner, int *maxch, int *status);
extern int zawset_(int *best_size, int *new_size, int *old_size, int *max_size);
extern int zcall0_(int *proc);
extern int zcall1_(int *proc, void *arg1);
extern int zcall2_(int *proc, void *arg1, void *arg2);
extern int zcall3_(int *proc, void *arg1, void *arg2, void *arg3);
extern int zcall4_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4);
extern int zcall5_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5);
extern int zcall6_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6);
extern int zcall7_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7);
extern int zcall8_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7, void *arg8);
extern int zcall9_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7, void *arg8, void *arg9);
extern int zcalla_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7, void *arg8, void *arg9, void *arg10);
extern void zdojmp_(int *jmpbuf, int *status);
extern int zfacss_(short *fname, int *mode, int *type, int *status);
extern int zfaloc_(short *fname, int *nbytes, int *status);
extern int zfchdr_(short *newdir, int *status);
extern int zfdele_(short *fname, int *status);
extern int zfgcwd_(short *outstr, int *maxch, int *status);
extern int zfinfo_(short *fname, int *finfo_struct, int *status);
extern int zopnbf_(short *osfn, int *mode, int *chan);
extern int zclsbf_(int *fd, int *status);
extern int zardbf_(int *chan, short *buf, int *maxbytes, int *offset);
extern int zawrbf_(int *chan, short *buf, int *nbytes, int *offset);
extern int zawtbf_(int *fd, int *status);
extern int zsttbf_(int *fd, int *param, int *lvalue);
extern int zopnks_(short *x_server, int *mode, int *chan);
extern int zclsks_(int *chan, int *status);
extern int zardks_(int *chan, short *buf, int *totbytes, int *loffset);
extern int zawrks_(int *chan, short *buf, int *totbytes, int *loffset);
extern int zawtks_(int *chan, int *status);
extern int zsttks_(int *chan, int *param, int *lvalue);
extern int zopnlp_(short *printer, int *mode, int *chan);
extern int zclslp_(int *chan, int *status);
extern int zardlp_(int *chan, short *buf, int *maxbytes, int *offset);
extern int zawrlp_(int *chan, short *buf, int *nbytes, int *offset);
extern int zawtlp_(int *chan, int *status);
extern int zsttlp_(int *chan, int *param, int *lvalue);
extern int zzopmt_(short *device, int *acmode, short *devcap, int *devpos, int *newfile, int *chan);
extern int zzclmt_(int *chan, int *devpos, int *o_status);
extern int zzrdmt_(int *chan, short *buf, int *maxbytes, int *offset);
extern int zzwrmt_(int *chan, short *buf, int *nbytes, int *offset);
extern int zzwtmt_(int *chan, int *devpos, int *o_status);
extern int zzstmt_(int *chan, int *param, int *lvalue);
extern int zzrwmt_(short *device, short *devcap, int *o_status);
extern int zopnnd_(short *pk_osfn, int *mode, int *chan);
extern int zclsnd_(int *fd, int *status);
extern int zardnd_(int *chan, short *buf, int *maxbytes, int *offset);
extern int zawrnd_(int *chan, short *buf, int *nbytes, int *offset);
extern int zawtnd_(int *fd, int *status);
extern int zsttnd_(int *fd, int *param, int *lvalue);
extern int zopnpl_(short *plotter, int *mode, int *chan);
extern int zclspl_(int *chan, int *status);
extern int zardpl_(int *chan, short *buf, int *maxbytes, int *offset);
extern int zawrpl_(int *chan, short *buf, int *nbytes, int *offset);
extern int zawtpl_(int *chan, int *status);
extern int zsttpl_(int *chan, int *param, int *lvalue);
extern int zopcpr_(short *osfn, int *inchan, int *outchan, int *pid);
extern int zclcpr_(int *pid, int *exit_status);
extern int zardpr_(int *chan, short *buf, int *maxbytes, int *loffset);
extern int zawrpr_(int *chan, short *buf, int *nbytes, int *loffset);
extern int zawtpr_(int *chan, int *status);
extern int zsttpr_(int *chan, int *param, int *lvalue);
extern int zopnsf_(short *osfn, int *mode, int *chan);
extern int zclssf_(int *fd, int *status);
extern int zardsf_(int *chan, short *buf, int *maxbytes, int *offset);
extern int zawrsf_(int *chan, short *buf, int *nbytes, int *offset);
extern int zawtsf_(int *fd, int *status);
extern int zsttsf_(int *fd, int *param, int *lvalue);
extern int zopntx_(short *osfn, int *mode, int *chan);
extern int zclstx_(int *fd, int *status);
extern int zflstx_(int *fd, int *status);
extern int zgettx_(int *fd, short *buf, int *maxchars, int *status);
extern int znottx_(int *fd, int *offset);
extern int zputtx_(int *fd, short *buf, int *nchars, int *status);
extern int zsektx_(int *fd, int *znottx_offset, int *status);
extern int zstttx_(int *fd, int *param, int *value);
extern int zopnty_(short *osfn, int *mode, int *chan);
extern int zclsty_(int *fd, int *status);
extern int zflsty_(int *fd, int *status);
extern int zgetty_(int *fd, short *buf, int *maxchars, int *status);
extern int znotty_(int *fd, int *offset);
extern int zputty_(int *fd, short *buf, int *nchars, int *status);
extern int zsekty_(int *fd, int *znotty_offset, int *status);
extern int zsttty_(int *fd, int *param, int *value);
extern int zfmkcp_(short *osfn, short *new_osfn, int *status);
extern int zfmkdr_(short *newdir, int *status);
extern int zfnbrk_(short *vfn, int *uroot_offset, int *uextn_offset);
extern int zfpath_(short *osfn, short *pathname, int *maxch, int *nchars);
extern int zfpoll_(int *pfds, int *nfds, int *timeout, int *npoll, int *status);
extern int zfprot_(short *fname, int *action, int *status);
extern int zfrnam_(short *oldname, short *newname, int *status);
extern int zfrmdr_(short *dir, int *status);
extern int zfsubd_(short *osdir, int *maxch, short *subdir, int *nchars);
extern int zfunc0_(int *proc);
extern int zfunc1_(int *proc, void *arg1);
extern int zfunc2_(int *proc, void *arg1, void *arg2);
extern int zfunc3_(int *proc, void *arg1, void *arg2, void *arg3);
extern int zfunc4_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4);
extern int zfunc5_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5);
extern int zfunc6_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6);
extern int zfunc7_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7);
extern int zfunc8_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7, void *arg8);
extern int zfunc9_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7, void *arg8, void *arg9);
extern int zfunca_(int *proc, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7, void *arg8, void *arg9, void *arg10);
extern int zfutim_(short *fname, int *atime, int *mtime, int *status);
extern int zfxdir_(short *osfn, short *osdir, int *maxch, int *nchars);
extern int zgcmdl_(short *cmd, int *maxch, int *status);
extern int zghost_(short *outstr, int *maxch);
extern int zgmtco_(int *gmtcor);
extern int zgtenv_(short *envvar, short *outstr, int *maxch, int *status);
extern int zgtime_(int *clock_time, int *cpu_time);
extern int zgtpid_(int *pid);
extern int zintpr_(int *pid, int *exception, int *status);
extern int zlocpr_(PFI proc, int *o_epa);
extern int zlocva_(short *variable, int *location);
extern int zmaloc_(int *buf, int *nbytes, int *status);
extern int zmfree_(int *buf, int *status);
extern int zopdir_(short *fname, int *chan);
extern int zcldir_(int *chan, int *status);
extern int zgfdir_(int *chan, short *outstr, int *maxch, int *status);
extern int zopdpr_(short *osfn, short *bkgfile, short *queue, int *jobcode);
extern int zcldpr_(int *jobcode, int *killflag, int *exit_status);
extern int zoscmd_(short *oscmd, short *stdin_file, short *stdout_file, short *stderr_file, int *status);
extern int zpanic_(int *errcode, short *errmsg);
extern int zraloc_(int *buf, int *nbytes, int *status);
extern int zwmsec_(int *msec);
extern int zxwhen_(int *sig_code, int *epa, int *old_epa);
extern int zxgmes_(int *os_exception, short *errmsg, int *maxch);
extern int zzepro_(void);
extern int zzpstr_(short *s1, short *s2);
extern int zzlstr_(short *s1, short *s2);
extern int zzsetk_(char *ospn, char *osbfn, int prtype, int isatty, int in, int out);
extern int zzstrt_(void);
extern int zzstop_(void);
