      SUBROUTINE CASCOD (LAB, TOKEN)
      INTEGER LAB, TOKEN
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER T, L, LB, UB, I, J, JUNK
      INTEGER CASLAB, LABGEN, GNBTOK
      INTEGER TOK (100)
      IF (.NOT.(SWTOP .LE. 0))GOTO 23000
      CALL SYNERR (24Hillegal case or default.)
      RETURN
23000 CONTINUE
      CALL INDENT (-1)
      CALL OUTGO (LAB + 1)
      XFER = 1
      L = LABGEN (1)
      IF (.NOT.(TOKEN .EQ. -91))GOTO 23002
23004 IF (.NOT.(CASLAB (LB, T) .NE. -1))GOTO 23005
      UB = LB
      IF (.NOT.(T .EQ. 45))GOTO 23006
      JUNK = CASLAB (UB, T)
23006 CONTINUE
      IF (.NOT.(LB .GT. UB))GOTO 23008
      CALL SYNERR (28Hillegal range in case label.)
      UB = LB
23008 CONTINUE
      IF (.NOT.(SWLAST + 3 .GT. 1000))GOTO 23010
      CALL BADERR (22Hswitch table overflow.)
23010 CONTINUE
      I = SWTOP + 3
23012 IF (.NOT.(I .LT. SWLAST))GOTO 23014
      IF (.NOT.(LB .LE. SWSTAK (I)))GOTO 23015
      GOTO 23014
23015 CONTINUE
      IF (.NOT.(LB .LE. SWSTAK (I+1)))GOTO 23017
      CALL SYNERR (21Hduplicate case label.)
23017 CONTINUE
23016 CONTINUE
23013 I = I + 3
      GOTO 23012
23014 CONTINUE
      IF (.NOT.(I .LT. SWLAST .AND. UB .GE. SWSTAK (I)))GOTO 23019
      CALL SYNERR (21Hduplicate case label.)
23019 CONTINUE
      J = SWLAST
23021 IF (.NOT.(J .GT. I))GOTO 23023
      SWSTAK (J+2) = SWSTAK (J-1)
23022 J = J - 1
      GOTO 23021
23023 CONTINUE
      SWSTAK (I) = LB
      SWSTAK (I + 1) = UB
      SWSTAK (I + 2) = L
      SWSTAK (SWTOP + 1) = SWSTAK (SWTOP + 1) + 1
      SWLAST = SWLAST + 3
      IF (.NOT.(T .EQ. 58))GOTO 23024
      GOTO 23005
23024 CONTINUE
      IF (.NOT.(T .NE. 44))GOTO 23026
      CALL SYNERR (20Hillegal case syntax.)
23026 CONTINUE
23025 CONTINUE
      GOTO 23004
23005 CONTINUE
      GOTO 23003
23002 CONTINUE
      T = GNBTOK (TOK, 100)
      IF (.NOT.(SWSTAK (SWTOP + 2) .NE. 0))GOTO 23028
      CALL ERROR (38Hmultiple defaults in switch statement.)
      GOTO 23029
23028 CONTINUE
      SWSTAK (SWTOP + 2) = L
23029 CONTINUE
23003 CONTINUE
      IF (.NOT.(T .EQ. -1))GOTO 23030
      CALL SYNERR (15Hunexpected EOF.)
      GOTO 23031
23030 CONTINUE
      IF (.NOT.(T .NE. 58))GOTO 23032
      CALL ERROR (39Hmissing colon in case or default label.)
23032 CONTINUE
23031 CONTINUE
      XFER = 0
      CALL OUTCON (L)
      CALL INDENT (1)
      RETURN
      END
C     LOGIC0  LOGICAL_COLUMN
