      SUBROUTINE DECLCO (ID)
      INTEGER ID(100)
      INTEGER NEWID(100), TOK, TOKBL
      INTEGER JUNK, LUDEF, EQUAL, GETTOK
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER XPTYP(9)
      INTEGER XPNTR(7)
      INTEGER XFUNC(7)
      INTEGER XSUBR(7)
      DATA XPTYP(1)/105/,XPTYP(2)/110/,XPTYP(3)/116/,XPTYP(4)/101/,XPTYP
     *(5)/103/,XPTYP(6)/101/,XPTYP(7)/114/,XPTYP(8)/32/,XPTYP(9)/-2/
      DATA XPNTR(1)/120/,XPNTR(2)/36/,XPNTR(3)/112/,XPNTR(4)/110/,XPNTR(
     *5)/116/,XPNTR(6)/114/,XPNTR(7)/-2/
      DATA XFUNC(1)/120/,XFUNC(2)/36/,XFUNC(3)/102/,XFUNC(4)/117/,XFUNC(
     *5)/110/,XFUNC(6)/99/,XFUNC(7)/-2/
      DATA XSUBR(1)/120/,XSUBR(2)/36/,XSUBR(3)/115/,XSUBR(4)/117/,XSUBR(
     *5)/98/,XSUBR(6)/114/,XSUBR(7)/-2/
      IF (.NOT.(LUDEF (ID, NEWID, XPPTBL) .EQ. 1))GOTO 23000
      IF (.NOT.(EQUAL (ID, XPNTR) .EQ. 1))GOTO 23002
      TOKBL = GETTOK (NEWID, 100)
      IF (.NOT.(TOKBL .EQ. 32))GOTO 23004
      TOK = GETTOK (NEWID, 100)
      GOTO 23005
23004 CONTINUE
      TOK = TOKBL
23005 CONTINUE
      IF (.NOT.(TOK .EQ.  -166 .AND. EQUAL (NEWID, XFUNC) .EQ. 1))GOTO 2
     *3006
      CALL OUTTAB
      CALL OUTSTR (XPTYP)
      JUNK = LUDEF (NEWID, NEWID, XPPTBL)
      CALL OUTSTR (NEWID)
      CALL EATUP
      CALL OUTDON
      CALL POICOD (0)
      GOTO 23007
23006 CONTINUE
      CALL PBSTR (NEWID)
      CALL POICOD (1)
23007 CONTINUE
      GOTO 23003
23002 CONTINUE
      IF (.NOT.(EQUAL (ID, XSUBR) .EQ. 1))GOTO 23008
      CALL OUTTAB
      CALL OUTSTR (NEWID)
      CALL EATUP
      CALL OUTDON
      GOTO 23009
23008 CONTINUE
      CALL OUTTAB
      CALL OUTSTR (NEWID)
      CALL OUTCH (32)
23009 CONTINUE
23003 CONTINUE
      GOTO 23001
23000 CONTINUE
      CALL SYNERR (32HInvalid x$type type declaration.)
23001 CONTINUE
      END
C     LOGIC0  LOGICAL_COLUMN
