      SUBROUTINE ENTDEF (NAME, DEFN, TABLE)
      INTEGER NAME (100), DEFN (100)
      INTEGER TABLE
      INTEGER LOOKUP
      INTEGER TEXT
      INTEGER SDUPL
      IF (.NOT.(LOOKUP (NAME, TEXT, TABLE) .EQ. 1))GOTO 23000
      CALL DSFREE (TEXT)
23000 CONTINUE
      CALL ENTER (NAME, SDUPL (DEFN), TABLE)
      RETURN
      END
