      SUBROUTINE ERRGO
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER SERRC0(13)
      DATA SERRC0(1)/105/,SERRC0(2)/102/,SERRC0(3)/32/,SERRC0(4)/40/,SER
     *RC0(5)/120/,SERRC0(6)/101/,SERRC0(7)/114/,SERRC0(8)/102/,SERRC0(9)
     */108/,SERRC0(10)/103/,SERRC0(11)/41/,SERRC0(12)/32/,SERRC0(13)/-2/
      IF (.NOT.(ERNAME .EQ. 1))GOTO 23000
      CALL OUTTAB
      IF (.NOT.(ESP .GT. 0))GOTO 23002
      IF (.NOT.(ERRSTK(ESP) .GT. 0))GOTO 23004
      CALL OUTSTR (SERRC0)
      CALL OGOTOS (ERRSTK(ESP)+2, 0)
23004 CONTINUE
      GOTO 23003
23002 CONTINUE
      CALL OUTSTR (SERRC0)
      CALL OGOTOS (RETLAB, 0)
      CALL OUTDON
23003 CONTINUE
      ERNAME = 0
23000 CONTINUE
      END
C     LOGIC0  LOGICAL_COLUMN
C     SERRC0  SERRCHK
