      SUBROUTINE GETDEF (TOKEN, TOKSIZ, DEFN, DEFSIZ)
      INTEGER TOKEN (100), DEFN (2048)
      INTEGER TOKSIZ, DEFSIZ
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER C, T, PTOKEN (100)
      INTEGER GTOK, NGETCH
      INTEGER I, NLPAR
      CALL SKPBLK
      C = GTOK (PTOKEN, 100)
      IF (.NOT.(C .EQ. 40))GOTO 23000
      T = 40
      GOTO 23001
23000 CONTINUE
      T = 32
      CALL PBSTR (PTOKEN)
23001 CONTINUE
      CALL SKPBLK
      IF (.NOT.(GTOK (TOKEN, TOKSIZ) .NE. -9))GOTO 23002
      CALL BADERR (22Hnon-alphanumeric name.)
23002 CONTINUE
      CALL SKPBLK
      C = GTOK (PTOKEN, 100)
      IF (.NOT.(T .EQ. 32))GOTO 23004
      CALL PBSTR (PTOKEN)
      I = 1
23006 CONTINUE
      C = NGETCH (C)
      IF (.NOT.(I .GT. DEFSIZ))GOTO 23009
      CALL BADERR (20Hdefinition too long.)
23009 CONTINUE
      DEFN (I) = C
      I = I + 1
23007 IF (.NOT.(C .EQ. 35 .OR. C .EQ. 10 .OR. C .EQ. -1))GOTO 23006
23008 CONTINUE
      IF (.NOT.(C .EQ. 35))GOTO 23011
      CALL PUTBAK (C)
23011 CONTINUE
      GOTO 23005
23004 CONTINUE
      IF (.NOT.(T .EQ. 40))GOTO 23013
      IF (.NOT.(C .NE. 44))GOTO 23015
      CALL BADERR (24Hmissing comma in define.)
23015 CONTINUE
      NLPAR = 0
      I = 1
23017 IF (.NOT.(NLPAR .GE. 0))GOTO 23019
      IF (.NOT.(I .GT. DEFSIZ))GOTO 23020
      CALL BADERR (20Hdefinition too long.)
      GOTO 23021
23020 CONTINUE
      IF (.NOT.(NGETCH (DEFN (I)) .EQ. -1))GOTO 23022
      CALL BADERR (20Hmissing right paren.)
      GOTO 23023
23022 CONTINUE
      IF (.NOT.(DEFN (I) .EQ. 40))GOTO 23024
      NLPAR = NLPAR + 1
      GOTO 23025
23024 CONTINUE
      IF (.NOT.(DEFN (I) .EQ. 41))GOTO 23026
      NLPAR = NLPAR - 1
23026 CONTINUE
23025 CONTINUE
23023 CONTINUE
23021 CONTINUE
23018 I = I + 1
      GOTO 23017
23019 CONTINUE
      GOTO 23014
23013 CONTINUE
      CALL BADERR (19Hgetdef is confused.)
23014 CONTINUE
23005 CONTINUE
      DEFN (I - 1) = -2
      RETURN
      END
C     LOGIC0  LOGICAL_COLUMN
