      INTEGER FUNCTION LEX (LEXSTR)
      INTEGER LEXSTR (100)
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER GNBTOK, T, C
      INTEGER LOOKUP, N
      INTEGER SDEFA0(8)
      DATA SDEFA0(1)/100/,SDEFA0(2)/101/,SDEFA0(3)/102/,SDEFA0(4)/97/,SD
     *EFA0(5)/117/,SDEFA0(6)/108/,SDEFA0(7)/116/,SDEFA0(8)/-2/
      LEX = GNBTOK (LEXSTR, 100)
23000 IF (.NOT.(LEX .EQ. 10))GOTO 23002
23001  LEX = GNBTOK (LEXSTR, 100)
      GOTO 23000
23002 CONTINUE
      IF (.NOT.(LEX .EQ. -1 .OR. LEX .EQ. 59 .OR. LEX .EQ. 123 .OR. LEX 
     *.EQ. 125))GOTO 23003
      RETURN
23003 CONTINUE
      IF (.NOT.(LEX .EQ. 48))GOTO 23005
      LEX = -89
      GOTO 23006
23005 CONTINUE
      IF (.NOT.(LEX .EQ. 37))GOTO 23007
      LEX = -85
      GOTO 23008
23007 CONTINUE
      IF (.NOT.(LEX .EQ.  -166))GOTO 23009
      LEX = -67
      GOTO 23010
23009 CONTINUE
      IF (.NOT.(LOOKUP (LEXSTR, LEX, RKWTBL) .EQ. 1))GOTO 23011
      IF (.NOT.(LEX .EQ. -90))GOTO 23013
      N = -1
23015 CONTINUE
      C = NGETCH (C)
      N = N + 1
23016 IF (.NOT.(C .NE. 32 .AND. C .NE. 9))GOTO 23015
23017 CONTINUE
      CALL PUTBAK (C)
      T = GNBTOK (LEXSTR, 100)
      CALL PBSTR (LEXSTR)
      IF (.NOT.(N .GT. 0))GOTO 23018
      CALL PUTBAK (32)
23018 CONTINUE
      CALL SCOPY (SDEFA0, 1, LEXSTR, 1)
      IF (.NOT.(T .NE. 58))GOTO 23020
      LEX = -80
23020 CONTINUE
23013 CONTINUE
      GOTO 23012
23011 CONTINUE
      LEX = -80
23012 CONTINUE
23010 CONTINUE
23008 CONTINUE
23006 CONTINUE
      RETURN
      END
C     LOGIC0  LOGICAL_COLUMN
C     SDEFA0  SDEFAULT
