      INTEGER FUNCTION NGETCH (C)
      INTEGER C
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER GETLIN, N, I
      IF (.NOT.(BUF (BP) .EQ. -2))GOTO 23000
      IF (.NOT.(GETLIN (BUF (3192), INFILE (LEVEL)) .EQ. -1))GOTO 23002
      C = -1
      GOTO 23003
23002 CONTINUE
      C = BUF (3192)
      BP = 3192 + 1
      IF (.NOT.(C .EQ. 35))GOTO 23004
      IF (.NOT.(BUF(BP) .EQ. 33 .AND. BUF(BP+1) .EQ. 35))GOTO 23006
      N = 0
      I=BP+3
23008 IF (.NOT.(BUF(I) .GE. 48 .AND. BUF(I) .LE. 57))GOTO 23010
      N = N * 10 + BUF(I) - 48
23009 I=I+1
      GOTO 23008
23010 CONTINUE
      LINECT (LEVEL) = N - 1
23006 CONTINUE
23004 CONTINUE
      LINECT (LEVEL) = LINECT (LEVEL) + 1
23003 CONTINUE
      GOTO 23001
23000 CONTINUE
      C = BUF (BP)
      BP = BP + 1
23001 CONTINUE
      NGETCH=(C)
      RETURN
      END
C     LOGIC0  LOGICAL_COLUMN
