      SUBROUTINE RATFOR
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER I, N
      INTEGER GETARG, RFOPEN
      INTEGER ARG (30)
      INTEGER DEFNS(1)
      DATA DEFNS(1)/-2/
      CALL INITKW
      IF (.NOT.(DEFNS (1) .NE. -2))GOTO 23000
      INFILE (1) = RFOPEN(DEFNS, 1)
      IF (.NOT.(INFILE (1) .EQ. -3))GOTO 23002
      CALL REMARK (37Hcan't open standard definitions file.)
      GOTO 23003
23002 CONTINUE
      CALL FINIT
      CALL PARSE
      CALL RFCLOS(INFILE (1))
23003 CONTINUE
23000 CONTINUE
      N = 1
      I = 1
23004 IF (.NOT.(GETARG (I, ARG, 30) .NE. -1))GOTO 23006
      N = N + 1
      CALL QUERY (32Husage:  ratfor [files] >outfile.)
      IF (.NOT.(ARG (1) .EQ. 45 .AND. ARG (2) .EQ. -2))GOTO 23007
      INFILE (1) = 0
      CALL FINIT
      GOTO 23008
23007 CONTINUE
      INFILE (1) = RFOPEN(ARG, 1)
      IF (.NOT.(INFILE (1) .EQ. -3))GOTO 23009
      CALL CANT (ARG)
      GOTO 23010
23009 CONTINUE
      CALL FINIT
      CALL SCOPY (ARG, 1, FNAMES, 1)
      FNAMP=1
23011 IF (.NOT.(FNAMES(FNAMP) .NE. -2))GOTO 23013
      IF (.NOT.(FNAMES(FNAMP) .EQ. 46 .AND. FNAMES(FNAMP+1) .EQ. 114))GO
     *TO 23014
      FNAMES(FNAMP+1) = 120
23014 CONTINUE
23012 FNAMP=FNAMP+1
      GOTO 23011
23013 CONTINUE
23010 CONTINUE
23008 CONTINUE
      CALL PARSE
      IF (.NOT.(INFILE (1) .NE. 0))GOTO 23016
      CALL RFCLOS(INFILE (1))
23016 CONTINUE
23005 I = I + 1
      GOTO 23004
23006 CONTINUE
      IF (.NOT.(N .EQ. 1))GOTO 23018
      INFILE (1) = 0
      CALL FINIT
      CALL PARSE
23018 CONTINUE
      CALL LNDICT
      END
C     LOGIC0  LOGICAL_COLUMN
