      SUBROUTINE SQUASH (ID)
      INTEGER ID(100)
      INTEGER JUNK, I, J
      INTEGER LOOKUP, LUDEF
      INTEGER NEWID(100), RECDID(100)
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      IF (.NOT.(BODY .EQ. 1 .AND. ERRTBL .NE. 0 .AND. ERNAME .EQ. 0))GOT
     *O 23000
      IF (.NOT.(LOOKUP (ID, JUNK, ERRTBL) .EQ. 1))GOTO 23002
      ERNAME = 1
23002 CONTINUE
23000 CONTINUE
      J = 1
      I=1
23004 IF (.NOT.(ID(I) .NE. -2))GOTO 23006
      IF (.NOT.(((65.LE.ID(I).AND.ID(I).LE.90).OR.(97.LE.ID(I).AND.ID(I)
     *.LE.122)) .OR. (48.LE.ID(I).AND.ID(I).LE.57)))GOTO 23007
      NEWID(J) = ID(I)
      J = J + 1
23007 CONTINUE
23005 I=I+1
      GOTO 23004
23006 CONTINUE
      NEWID(J) = -2
      IF (.NOT.(I-1 .LT. 6 .AND. I .EQ. J))GOTO 23009
      RETURN
23009 CONTINUE
      IF (.NOT.(LOOKUP (ID, JUNK, FKWTBL) .EQ. 1))GOTO 23011
      RETURN
23011 CONTINUE
      IF (.NOT.(LUDEF (ID, RECDID, NAMTBL) .EQ. 1))GOTO 23013
      CALL SCOPY (RECDID, 1, ID, 1)
      RETURN
23013 CONTINUE
      CALL MAPID (NEWID)
      IF (.NOT.(LOOKUP (NEWID, JUNK, GENTBL) .EQ. 1))GOTO 23015
      CALL SYNERR (39HWarning: identifier mapping not unique.)
      CALL UNIQID (NEWID)
23015 CONTINUE
      CALL ENTDEF (NEWID, ID, GENTBL)
      CALL ENTDEF (ID, NEWID, NAMTBL)
      CALL SCOPY (NEWID, 1, ID, 1)
      END
C     LOGIC0  LOGICAL_COLUMN
