      SUBROUTINE SWEND (LAB)
      INTEGER LAB
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER LB, UB, N, I, J, SWN
      INTEGER SIF(5)
      INTEGER SLT(10)
      INTEGER SGT(5)
      INTEGER SGOTO(7)
      INTEGER SEQ(5)
      INTEGER SGE(5)
      INTEGER SLE(5)
      INTEGER SAND(6)
      DATA SIF(1)/105/,SIF(2)/102/,SIF(3)/32/,SIF(4)/40/,SIF(5)/-2/
      DATA SLT(1)/46/,SLT(2)/108/,SLT(3)/116/,SLT(4)/46/,SLT(5)/49/,SLT(
     *6)/46/,SLT(7)/111/,SLT(8)/114/,SLT(9)/46/,SLT(10)/-2/
      DATA SGT(1)/46/,SGT(2)/103/,SGT(3)/116/,SGT(4)/46/,SGT(5)/-2/
      DATA SGOTO(1)/103/,SGOTO(2)/111/,SGOTO(3)/116/,SGOTO(4)/111/,SGOTO
     *(5)/32/,SGOTO(6)/40/,SGOTO(7)/-2/
      DATA SEQ(1)/46/,SEQ(2)/101/,SEQ(3)/113/,SEQ(4)/46/,SEQ(5)/-2/
      DATA SGE(1)/46/,SGE(2)/103/,SGE(3)/101/,SGE(4)/46/,SGE(5)/-2/
      DATA SLE(1)/46/,SLE(2)/108/,SLE(3)/101/,SLE(4)/46/,SLE(5)/-2/
      DATA SAND(1)/46/,SAND(2)/97/,SAND(3)/110/,SAND(4)/100/,SAND(5)/46/
     *,SAND(6)/-2/
      SWN = SWVSTK(SWVLEV)
      SWVLEV = MAX0(0, SWVLEV - 1)
      LB = SWSTAK (SWTOP + 3)
      UB = SWSTAK (SWLAST - 2)
      N = SWSTAK (SWTOP + 1)
      CALL OUTGO (LAB + 1)
      IF (.NOT.(SWSTAK (SWTOP + 2) .EQ. 0))GOTO 23000
      SWSTAK (SWTOP + 2) = LAB + 1
23000 CONTINUE
      XFER = 0
      CALL INDENT (-1)
      CALL OUTCON (LAB)
      CALL INDENT (1)
      IF (.NOT.(N .GE. 3 .AND. UB - LB + 1 .LT. 2 * N))GOTO 23002
      IF (.NOT.(LB .NE. 1))GOTO 23004
      CALL OUTTAB
      CALL SWVAR (SWN)
      CALL OUTCH (61)
      CALL SWVAR (SWN)
      IF (.NOT.(LB .LT. 1))GOTO 23006
      CALL OUTCH (43)
23006 CONTINUE
      CALL OUTNUM (-LB + 1)
      CALL OUTDON
23004 CONTINUE
      IF (.NOT.(SWINRG .EQ. 0))GOTO 23008
      CALL OUTTAB
      CALL OUTSTR (SIF)
      CALL SWVAR (SWN)
      CALL OUTSTR (SLT)
      CALL SWVAR (SWN)
      CALL OUTSTR (SGT)
      CALL OUTNUM (UB - LB + 1)
      CALL OUTCH (41)
      CALL OUTCH (32)
      CALL OUTGO (SWSTAK (SWTOP + 2))
23008 CONTINUE
      CALL OUTTAB
      CALL OUTSTR (SGOTO)
      J = LB
      I = SWTOP + 3
23010 IF (.NOT.(I .LT. SWLAST))GOTO 23012
23013 IF (.NOT.(J .LT. SWSTAK (I)))GOTO 23015
      CALL OUTNUM (SWSTAK (SWTOP + 2))
      CALL OUTCH (44)
23014 J = J + 1
      GOTO 23013
23015 CONTINUE
      J = SWSTAK (I + 1) - SWSTAK (I)
23016 IF (.NOT.(J .GE. 0))GOTO 23018
      CALL OUTNUM (SWSTAK (I + 2))
23017 J = J - 1
      GOTO 23016
23018 CONTINUE
      J = SWSTAK (I + 1) + 1
      IF (.NOT.(I .LT. SWLAST - 3))GOTO 23019
      CALL OUTCH (44)
23019 CONTINUE
23011 I = I + 3
      GOTO 23010
23012 CONTINUE
      CALL OUTCH (41)
      CALL OUTCH (44)
      CALL SWVAR (SWN)
      CALL OUTDON
      GOTO 23003
23002 CONTINUE
      IF (.NOT.(N .GT. 0))GOTO 23021
      I = SWTOP + 3
23023 IF (.NOT.(I .LT. SWLAST))GOTO 23025
      CALL OUTTAB
      CALL OUTSTR (SIF)
      CALL SWVAR (SWN)
      IF (.NOT.(SWSTAK (I) .EQ. SWSTAK (I+1)))GOTO 23026
      CALL OUTSTR (SEQ)
      CALL OUTNUM (SWSTAK (I))
      GOTO 23027
23026 CONTINUE
      CALL OUTSTR (SGE)
      CALL OUTNUM (SWSTAK (I))
      CALL OUTSTR (SAND)
      CALL SWVAR (SWN)
      CALL OUTSTR (SLE)
      CALL OUTNUM (SWSTAK (I + 1))
23027 CONTINUE
      CALL OUTCH (41)
      CALL OUTCH (32)
      CALL OUTGO (SWSTAK (I + 2))
23024 I = I + 3
      GOTO 23023
23025 CONTINUE
      IF (.NOT.(LAB + 1 .NE. SWSTAK (SWTOP + 2)))GOTO 23028
      CALL OUTGO (SWSTAK (SWTOP + 2))
23028 CONTINUE
23021 CONTINUE
23003 CONTINUE
      CALL INDENT (-1)
      CALL OUTCON (LAB + 1)
      SWLAST = SWTOP
      SWTOP = SWSTAK (SWTOP)
      SWINRG = 0
      RETURN
      END
C     LOGIC0  LOGICAL_COLUMN
