      SUBROUTINE THENCO (TOK, LAB)
      INTEGER LAB, TOK
      COMMON /CDEFIO/ BP, BUF (4096)
      INTEGER BP
      INTEGER BUF
      COMMON /CFNAME/ FCNAME (30)
      INTEGER FCNAME
      COMMON /CFOR/ FORDEP, FORSTK (200)
      INTEGER FORDEP
      INTEGER FORSTK
      COMMON /CGOTO/ XFER
      INTEGER XFER
      COMMON /CLABEL/ LABEL, RETLAB, MEMFLG, COL, LOGIC0
      INTEGER LABEL
      INTEGER RETLAB
      INTEGER MEMFLG
      INTEGER COL
      INTEGER LOGIC0
      COMMON /CLINE/ LEVEL, LINECT (5), INFILE (5), FNAMP, FNAMES ( 150)
      INTEGER LEVEL
      INTEGER LINECT
      INTEGER INFILE
      INTEGER FNAMP
      INTEGER FNAMES
      COMMON /CMACRO/ CP, EP, EVALST (500), DEFTBL
      INTEGER CP
      INTEGER EP
      INTEGER EVALST
      INTEGER DEFTBL
      COMMON /COUTLN/ OUTP, OUTBUF (74)
      INTEGER OUTP
      INTEGER OUTBUF
      COMMON /CSBUF/ SBP, SBUF(2048), SMEM(240)
      INTEGER SBP
      INTEGER SBUF
      INTEGER SMEM
      COMMON /CSWTCH/ SWTOP, SWLAST, SWSTAK(1000), SWVNUM, SWVLEV, SWVST
     *K(10), SWINRG
      INTEGER SWTOP
      INTEGER SWLAST
      INTEGER SWSTAK
      INTEGER SWVNUM
      INTEGER SWVLEV
      INTEGER SWVSTK
      INTEGER SWINRG
      COMMON /CKWORD/ RKWTBL
      INTEGER RKWTBL
      COMMON /CLNAME/ FKWTBL, NAMTBL, GENTBL, ERRTBL, XPPTBL
      INTEGER FKWTBL
      INTEGER NAMTBL
      INTEGER GENTBL
      INTEGER ERRTBL
      INTEGER XPPTBL
      COMMON /ERCHEK/ ERNAME, BODY, ESP, ERRSTK(30)
      INTEGER ERNAME
      INTEGER BODY
      INTEGER ESP
      INTEGER ERRSTK
      INTEGER MEM( 60000)
      COMMON/CDSMEM/MEM
      INTEGER SIFERR(20)
      INTEGER SIFNO0(15)
      DATA SIFERR(1)/105/,SIFERR(2)/102/,SIFERR(3)/32/,SIFERR(4)/40/,SIF
     *ERR(5)/46/,SIFERR(6)/110/,SIFERR(7)/111/,SIFERR(8)/116/,SIFERR(9)/
     *46/,SIFERR(10)/120/,SIFERR(11)/101/,SIFERR(12)/114/,SIFERR(13)/112
     */,SIFERR(14)/111/,SIFERR(15)/112/,SIFERR(16)/40/,SIFERR(17)/41/,SI
     *FERR(18)/41/,SIFERR(19)/32/,SIFERR(20)/-2/
      DATA SIFNO0(1)/105/,SIFNO0(2)/102/,SIFNO0(3)/32/,SIFNO0(4)/40/,SIF
     *NO0(5)/120/,SIFNO0(6)/101/,SIFNO0(7)/114/,SIFNO0(8)/112/,SIFNO0(9)
     */111/,SIFNO0(10)/112/,SIFNO0(11)/40/,SIFNO0(12)/41/,SIFNO0(13)/41/
     *,SIFNO0(14)/32/,SIFNO0(15)/-2/
      XFER = 0
      CALL OUTNUM (LAB+2)
      CALL OUTTAB
      IF (.NOT.(TOK .EQ. -98))GOTO 23000
      CALL OUTSTR (SIFERR)
      GOTO 23001
23000 CONTINUE
      CALL OUTSTR (SIFNO0)
23001 CONTINUE
      CALL OUTGO (LAB)
      ESP = ESP - 1
      CALL INDENT (1)
      RETURN
      END
C     SIFNO0  SIFNOERR
C     LOGIC0  LOGICAL_COLUMN
