task	mk1dspec	= t_mk1dspec,
	mk2dspec	= t_mk2dspec,
	mkechelle	= t_mkechelle,
	mkheader	= t_mkheader,
	mknoise		= t_mknoise,
	mkobjects	= t_mkobjects,
	mkpattern	= t_mkpattern,
	starlist	= t_starlist,
	gallist		= t_gallist
