#include <f2c/sys/sys.h>
#include <f2c/sys/vops.h>
#include <f2c/tables/tbtables.h>
#include "../../lib/pttables/f2c_proto.h"
#include "../daolib/f2c_proto.h"
#include "../psf/f2c_proto.h"
#include "../peak/f2c_proto.h"
#include "../nstar/f2c_proto.h"
#include "f2c_proto.h"
