#include <f2c/sys/sys.h>
#include <f2c/sys/vops.h>
#include <f2c/sys/ex.h>
#include <f2c/math/nlfit.h>
#include <f2c/pkg/xtools.h>
#include "../io/f2c_proto.h"
#include "../parser/f2c_proto.h"
#include "../mctable/f2c_proto.h"
#include "f2c_proto.h"
