#!/bin/csh -x

mkpkg xflags="-c -g" libsys.a

/bin/rm -f zzfoo.x
generic -o zzfoo.x zzfoo.gx
#cc -c -g $HSI_CF zmaloc.c zmfree.c zraloc.c
xc -g -c -/K -F zzfoo.x
#xc -g zzfoo.o zmaloc.o zraloc.o zmfree.o libsys.a #-lefence
xc -g zzfoo.o libsys.a #-lefence
