# KNET.H -- Include in source files which access the IRAF kernel if network
# capabilities are desired.  This include file should be permanently referenced
# in such source files.  If a system is to be configured without networking
# capabilities, define KNET to be false and comment out the remaining defines
# before compilation of the system libraries.

define	KNET	true

define	zardbf	kardbf
define	zardgd	kardgd
define	zardlp	kardlp
define	zardpl	kardpl
define	zardpr	kardpr
define	zardsf	kardsf
define	zawrbf	kawrbf
define	zawrgd	kawrgd
define	zawrlp	kawrlp
define	zawrpl	kawrpl
define	zawrpr	kawrpr
define	zawrsf	kawrsf
define	zawtbf	kawtbf
define	zawtgd	kawtgd
define	zawtlp	kawtlp
define	zawtpl	kawtpl
define	zawtpr	kawtpr
define	zawtsf	kawtsf
define	zclcpr	kclcpr
define	zcldir	kcldir
define	zcldpr	kcldpr
define	zclsbf	kclsbf
define	zclsgd	kclsgd
define	zclslp	kclslp
define	zclspl	kclspl
define	zclspr	kclspr
define	zclssf	kclssf
define	zclstx	kclstx
define	zclsty	kclsty
define	zdvall	kdvall
define	zdvown	kdvown
define	zfacss	kfacss
define	zfaloc	kfaloc
define	zfchdr	kfchdr
define	zfdele	kfdele
define	zfgcwd	kfgcwd
define	zfinfo	kfinfo
define	zflstx	kflstx
define	zflsty	kflsty
define	zfmkcp	kfmkcp
define	zfmkdr	kfmkdr
define	zfodpr	kfodpr
define	zfpath	kfpath
define	zfprot	kfprot
define	zfrnam	kfrnam
define	zfrmdr	kfrmdr
define	zfsubd	kfsubd
define	zfutim	kfutim
define	zfxdir	kfxdir
define	zgettx	kgettx
define	zgetty	kgetty
define	zgfdir	kgfdir
define	zintpr	kintpr
define	znottx	knottx
define	znotty	knotty
define	zopcpr	kopcpr
define	zopdir	kopdir
define	zopdpr	kopdpr
define	zopnbf	kopnbf
define	zopngd	kopngd
define	zopnlp	kopnlp
define	zopnpl	kopnpl
define	zopnpr	kopnpr
define	zopnsf	kopnsf
define	zopntx	kopntx
define	zopnty	kopnty
define	zoscmd	koscmd
define	zputtx	kputtx
define	zputty	kputty
define	zsektx	ksektx
define	zsekty	ksekty
define	zsttbf	ksttbf
define	zsttgd	ksttgd
define	zsttlp	ksttlp
define	zsttpl	ksttpl
define	zsttpr	ksttpr
define	zsttsf	ksttsf
define	zstttx	kstttx
define	zsttty	ksttty
define	ztsdpr	ktsdpr
define	zzclmt	kzclmt
define	zzopmt	kzopmt
define	zzrdmt	kzrdmt
define	zzrwmt	kzrwmt
define	zzstmt	kzstmt
define	zzwrmt	kzwrmt
define	zzwtmt	kzwtmt
